## 张量练习

In [2]:
import torch
import numpy as np

### 1. 从列表直接生成张量

In [4]:
x = [[1,2,3],[2,3,4],[3,4,5]]
x_t = torch.tensor(x)
print(x_t, type(x_t))

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]) <class 'torch.Tensor'>


### 2. 通过numpy数组生成张量

In [5]:
nd_array = np.array(x)
nd_tensor = torch.from_numpy(nd_array)
print(nd_tensor, type(nd_tensor))

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]) <class 'torch.Tensor'>


### 3. 从已有张量生成新的张量

In [6]:
y_t = torch.ones_like(x_t, dtype=torch.float32)
print(y_t)
z_t = torch.rand_like(x_t, dtype=torch.float32)
print(x_t)
h_t = torch.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
