## 张量练习

In [1]:
import torch
import numpy as np

## 张量的生成
### 1. 从列表直接生成张量

In [2]:
x = [[1,2,3],[2,3,4],[3,4,5]]
x_t = torch.tensor(x)
print(x_t, type(x_t))

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]) <class 'torch.Tensor'>


### 2. 通过numpy数组生成张量

In [3]:
nd_array = np.array(x)
nd_tensor = torch.from_numpy(nd_array)
print(nd_tensor, type(nd_tensor))

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]], dtype=torch.int32) <class 'torch.Tensor'>


### 3. 从已有张量生成新的张量

In [7]:
# ons_like: 全1的张量
# randn_like: 随机张量
# zero_like: 全0张量
y_t = torch.ones_like(x_t, dtype=torch.float32)
print(y_t)
z_t = torch.rand_like(x_t, dtype=torch.float32)
print(x_t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


### 4. 指定张量形状

In [8]:
# ones, zeros, randn...
shape = (2,3,2)
shape_t1 = torch.randint(low=0, high=10, size=shape)
shape_t2 = torch.randn(size=shape)
print(shape_t1)
print(shape_t2)

tensor([[[6, 9],
         [9, 4],
         [6, 8]],

        [[4, 2],
         [1, 4],
         [3, 7]]])
tensor([[[-0.7264,  0.0824],
         [-0.6292,  1.6502],
         [-1.5764, -0.5806]],

        [[-0.5095, -2.4726],
         [ 1.0115,  0.3893],
         [ 0.1609,  0.8710]]])


## 张量的属性：形状，运算设备，等等

In [9]:
print(shape_t1.device)
print(shape_t1.shape)
print(shape_t1.dtype)

cpu
torch.Size([2, 3, 2])
torch.int64


### 判断cuda可用

In [10]:
print(torch.cuda.is_available())

True


## 张量运算
### 切片, 拼接，矩阵乘法，自动赋值

In [22]:
cal_t = torch.ones((3,3),dtype=torch.float32).to('cuda')
cal_t[:, 2] = -3
print(cal_t)

tensor([[ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.]], device='cuda:0')


In [23]:
cal_t1 = torch.cat([cal_t, cal_t, cal_t], dim=0)
print(cal_t1)

tensor([[ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.],
        [ 1.,  1., -3.]], device='cuda:0')


In [24]:
cal_t2 = torch.mul(cal_t, cal_t)
print(cal_t2)

tensor([[1., 1., 9.],
        [1., 1., 9.],
        [1., 1., 9.]], device='cuda:0')


In [25]:
cal_t3 = cal_t[1, :].add_(9)
print(cal_t)

tensor([[ 1.,  1., -3.],
        [10., 10.,  6.],
        [ 1.,  1., -3.]], device='cuda:0')
